# Generated by Django 3.2.5 on 2021-07-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link_repository',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
