# Generated by Django 3.2.5 on 2021-07-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210725_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
